language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cppcheck
      - libboost-date-time-dev
      - libboost-system-dev
      - libboost-thread-dev

script:
  - cppcheck --error-exitcode=1 --quiet .
  - mkdir -p build
  - pushd build
  - cmake ..
  - make
  - popd
