language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cppcheck libboost-date-time-dev libboost-system-dev libboost-thread-dev

script:
  - cppcheck --error-exitcode=1 --quiet .
  - mkdir -p build
  - pushd build
  - cmake ..
  - make
  - popd
