language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libboost-date-time-dev libboost-thread-dev

script:
  - mkdir -p build
  - pushd build
  - cmake ..
  - make
  - popd
